-- Migration 002: Enums (alignés code TypeScript)

DO $$ BEGIN
  CREATE TYPE user_role AS ENUM ('SUPER_ADMIN', 'ADMIN', 'ANALYSTE_SIG', 'CLIENT');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  CREATE TYPE organization_type AS ENUM (
    'INSTITUTION', 'GOUVERNEMENT', 'ONG', 'ACADEMIQUE', 'INTERNATIONAL', 'AUTRE'
  );
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  CREATE TYPE territory_type AS ENUM ('DISTRICT', 'COMMUNE');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  CREATE TYPE import_status AS ENUM ('BROUILLON', 'EN_COURS', 'TERMINE', 'ECHEC');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  CREATE TYPE import_file_type AS ENUM ('GEOJSON', 'JSON', 'CSV');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  CREATE TYPE matching_status AS ENUM ('EN_ATTENTE', 'VALIDE', 'REJETE', 'AMBIGU');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  CREATE TYPE matching_method AS ENUM (
    'CODE_ADMINISTRATIF', 'NOM_NORMALISE', 'ALIAS', 'FUZZY_MATCHING', 'MANUEL'
  );
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  CREATE TYPE event_type AS ENUM (
    'CYCLONE', 'INONDATION', 'SECHERESSE', 'FORTE_PLUIE', 'VENT_VIOLENT',
    'GLISSEMENT_TERRAIN', 'FEU_VEGETATION', 'AUTRE'
  );
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  CREATE TYPE event_status AS ENUM ('BROUILLON', 'PREVISION', 'ACTIF', 'SUIVI', 'CLOTURE');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  CREATE TYPE severity_level AS ENUM ('FAIBLE', 'MODEREE', 'ELEVEE', 'EXTREME');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  CREATE TYPE track_type AS ENUM ('OBSERVEE', 'PREVUE');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  CREATE TYPE risk_phase AS ENUM ('AVANT', 'PENDANT', 'APRES', 'RETABLISSEMENT');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  CREATE TYPE risk_level AS ENUM ('FAIBLE', 'MODERE', 'ELEVE', 'EXTREME');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  CREATE TYPE alert_status AS ENUM ('BROUILLON', 'PUBLIEE', 'ARCHIVEE', 'EXPIREE');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  CREATE TYPE alert_type AS ENUM (
    'CYCLONE', 'INONDATION', 'FORTE_PLUIE', 'VENT_VIOLENT',
    'SECHERESSE', 'INFORMATION', 'URGENCE'
  );
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  CREATE TYPE report_format AS ENUM ('PDF', 'CSV', 'XLSX', 'GEOJSON', 'PNG');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  CREATE TYPE ai_message_role AS ENUM ('UTILISATEUR', 'ASSISTANT', 'OUTIL', 'SYSTEME');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;
